### ISSUE TITLE
what's new?

### ISSUE THREAD

**Issue by sossnowski** [SenorKarlos/mbtiles#1]
Hey dude it is a great idea, maybe some update? Some new tiles :D

**Comment by SenorKarlos** [comment]
I am no longer actively mapping so just keeping the last ones I did up on a free VPS and cheap domain. Feel free to follow the same directions I used, it's about $5 a run on a Linode (or whatever they're called now)

If you do and want to share, I'll upload the new file if you find a way to get it to me.
